name: Next.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js with caching
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Next.js app (Turbo by default)
      env:
        NODE_ENV: production
      run: npm run build

    - name: Restart Next.js app with PM2
      run: |
        pm2 delete all || true
        pm2 start "npm run start -- -p 3000"
