name: Next.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install --frozen-lockfile --no-cache
      env:
        NODE_OPTIONS: "--max-old-space-size=2048"

    - name: Build Next.js app
      env:
        NODE_ENV: production
      run: bun run build

    - name: Restart Next.js app with PM2
      run: |
        pm2 delete all || true
        pm2 start "bun run start -- -p 3000"
