name: Next.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Start Next.js app with PM2
      run: |
        pm2 delete all || true
        pm2 start "npm run start -- -p 3000"
